# Image with build dependencies for some django related packages

FROM python:3.11-alpine

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# hadolint ignore=DL3013
RUN pip install -U --no-cache-dir pip

RUN apk add --no-cache \
    # dependencies for building Python packages \
    make python3-dev \
    # libxml dependencies \
    libxslt-dev \
    # psycopg2 dependencies \
    libpq-dev