name: Docker build node-dev

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Docker build
        uses: tiwariav/github-actions/docker-build@v1
        with:
          context: src
          file: ./src/images/node-dev/Dockerfile
          image: tiwariav/node-dev