name: Publish Docker image

on:
  push:
    branches:
      - "master"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: https://docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./node-with-aws-cli
          push: true
          tags: |
            tiwariav/dockers/node-with-aws-cli:latest
            docker.pkg.github.com/tiwariav/dockers/node-with-aws-cli:latest
